# Generated by Django 6.0.3 on 2026-04-06 01:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partner_type', models.CharField(choices=[('hotel', 'Hotel'), ('restaurant', 'Restaurant'), ('coffee', 'Coffee'), ('agency', 'Agency')], max_length=20)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('description', models.TextField()),
                ('profile_photo', models.ImageField(blank=True, null=True, upload_to='partners/')),
                ('is_approved', models.BooleanField(default=False)),
                ('verification_document', models.FileField(upload_to='verifications/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='partner', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating_avg', models.FloatField(default=0.0)),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='locations.city')),
                ('partner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='hotel', to='partners.partner')),
            ],
        ),
        migrations.CreateModel(
            name='Coffee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating_avg', models.FloatField(default=0.0)),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='locations.city')),
                ('partner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='coffee', to='partners.partner')),
            ],
        ),
        migrations.CreateModel(
            name='Agency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating_avg', models.FloatField(default=0.0)),
                ('partner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='agency', to='partners.partner')),
            ],
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating_avg', models.FloatField(default=0.0)),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='locations.city')),
                ('partner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='restaurant', to='partners.partner')),
            ],
        ),
    ]
